--- 
phases:
  install:
    runtime-versions:
      docker: 18
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t lizitong/node-server ."
      - "docker tag lizitong/node-server lizitong/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push lizitong/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login -u lizitong -p 1234.com"
version: 0.2

